"""Workspace-scoped GraphRAG contracts and adapters."""

from kb_core_ui.rag.contracts import (
    AMBIGUOUS,
    EXTRACTED,
    INFERRED,
    SCHEMA_VERSION,
    Citation,
    GraphEnvelope,
    GraphNode,
    GraphRelationship,
    TextChunk,
    from_kb_core_graph,
    stable_record_id,
)
from kb_core_ui.rag.config import RagConfig
from kb_core_ui.rag.normalizer import (
    NormalizationError,
    NormalizationLimits,
    NormalizationResult,
    RejectedRecord,
    normalize_kb_core_graph,
)
from kb_core_ui.rag.ingestion import (
    DocumentChunk,
    DocumentSetIngestor,
    GraphDocument,
    GraphDocumentExtractor,
    GraphDocumentNode,
    GraphDocumentRelationship,
    IngestionError,
    RepoGraphIngestor,
    SourceDocument,
    load_document_files,
)
from kb_core_ui.rag.indexing import (
    INDEX_VERSION,
    EmbeddingProvider,
    FalkorGraphDocumentLoader,
    FalkorVectorBridge,
    FalkorVectorTypes,
    GraphDocumentTypes,
    HybridRetriever,
    IndexBuildResult,
    IndexingError,
    RetrievalHit,
    RetrievalIndexer,
    SearchCandidate,
)
from kb_core_ui.rag.falkordb_adapter import (
    AdapterError,
    AdapterHealth,
    FalkorDBAdapter,
    FalkorDBDriver,
    UnsafeCypherError,
    validate_read_only_cypher,
)
from kb_core_ui.rag.reconciler import (
    ReconcileError,
    ReconcileResult,
    SourceManifest,
    SourceReconciler,
    StageCounts,
    source_version,
)
from kb_core_ui.rag.manager import WorkspaceManager
from kb_core_ui.rag.chat_contract import (
    SSE_EVENT_CANCELLED,
    SSE_EVENT_COMPLETED,
    SSE_EVENT_ERROR,
    SSE_EVENT_HEARTBEAT,
    SSE_EVENT_QUEUED,
    SSE_EVENT_TOKEN,
    TERMINAL_SSE_EVENTS,
    ChatManagerError,
)
from kb_core_ui.rag.workspaces import (
    RUN_CANCELLED,
    RUN_FAILED,
    RUN_QUEUED,
    RUN_RUNNING,
    RUN_SUCCEEDED,
    SOURCE_DELETING,
    SOURCE_FAILED,
    SOURCE_INGESTING,
    SOURCE_PENDING,
    SOURCE_READY,
    WORKSPACE_ACTIVE,
    WORKSPACE_DELETING,
    IngestionRun,
    Source,
    Workspace,
    WorkspaceError,
    WorkspaceRegistry,
    workspace_graph_name,
)

_OPTIONAL_EXPORTS = {
    "ChatManager": "kb_core_ui.rag.chat_manager",
    "HashingEmbeddingProvider": "kb_core_ui.rag.chat_manager",
    "chat_contract_payload": "kb_core_ui.rag.chat_manager",
    "ChatHistoryStore": "kb_core_ui.rag.persistence",
    "ChatThreadAdapter": "kb_core_ui.rag.persistence",
    "FakeChatBackend": "kb_core_ui.rag.persistence",
    "FakeChatThreadAdapter": "kb_core_ui.rag.persistence",
    "PersistedTurn": "kb_core_ui.rag.persistence",
    "PersistenceError": "kb_core_ui.rag.persistence",
    "thread_key": "kb_core_ui.rag.persistence",
    "validate_thread_id": "kb_core_ui.rag.persistence",
    "ALLOWED_LABELS_AND_RELATIONSHIPS": "kb_core_ui.rag.workflow",
    "ALLOWED_PROPERTIES": "kb_core_ui.rag.workflow",
    "ALLOWED_PARAMETERS": "kb_core_ui.rag.workflow",
    "CANCELLED_TEXT": "kb_core_ui.rag.workflow",
    "INSUFFICIENT_EVIDENCE_TEXT": "kb_core_ui.rag.workflow",
    "PROVIDER_UNAVAILABLE_TEXT": "kb_core_ui.rag.workflow",
    "ChatAnswer": "kb_core_ui.rag.workflow",
    "ChatModel": "kb_core_ui.rag.workflow",
    "ChatRequest": "kb_core_ui.rag.workflow",
    "ChatResponse": "kb_core_ui.rag.workflow",
    "ChatWorkflow": "kb_core_ui.rag.workflow",
    "ChatWorkflowState": "kb_core_ui.rag.workflow",
    "EvidenceItem": "kb_core_ui.rag.workflow",
    "FakeChatModel": "kb_core_ui.rag.workflow",
    "ProviderError": "kb_core_ui.rag.workflow",
    "ProviderTransientError": "kb_core_ui.rag.workflow",
    "RetrievalLimits": "kb_core_ui.rag.workflow",
    "WorkflowError": "kb_core_ui.rag.workflow",
    "validate_generated_cypher": "kb_core_ui.rag.workflow",
}


def __getattr__(name: str):
    """Load LangGraph-backed exports only when callers request them."""

    module_name = _OPTIONAL_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    from importlib import import_module

    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value

__all__ = [
    "AMBIGUOUS",
    "EXTRACTED",
    "INFERRED",
    "SCHEMA_VERSION",
    "Citation",
    "GraphEnvelope",
    "GraphNode",
    "GraphRelationship",
    "TextChunk",
    "from_kb_core_graph",
    "stable_record_id",
    "RagConfig",
    "NormalizationError",
    "NormalizationLimits",
    "NormalizationResult",
    "RejectedRecord",
    "normalize_kb_core_graph",
    "DocumentChunk",
    "DocumentSetIngestor",
    "GraphDocument",
    "GraphDocumentExtractor",
    "GraphDocumentNode",
    "GraphDocumentRelationship",
    "IngestionError",
    "RepoGraphIngestor",
    "SourceDocument",
    "load_document_files",
    "INDEX_VERSION",
    "EmbeddingProvider",
    "FalkorGraphDocumentLoader",
    "FalkorVectorBridge",
    "FalkorVectorTypes",
    "GraphDocumentTypes",
    "HybridRetriever",
    "IndexBuildResult",
    "IndexingError",
    "RetrievalHit",
    "RetrievalIndexer",
    "SearchCandidate",
    "AdapterError",
    "AdapterHealth",
    "FalkorDBAdapter",
    "FalkorDBDriver",
    "UnsafeCypherError",
    "validate_read_only_cypher",
    "ReconcileError",
    "ReconcileResult",
    "SourceManifest",
    "SourceReconciler",
    "StageCounts",
    "source_version",
    "WorkspaceManager",
    "SSE_EVENT_CANCELLED",
    "SSE_EVENT_COMPLETED",
    "SSE_EVENT_ERROR",
    "SSE_EVENT_HEARTBEAT",
    "SSE_EVENT_QUEUED",
    "SSE_EVENT_TOKEN",
    "TERMINAL_SSE_EVENTS",
    "ChatManager",
    "ChatManagerError",
    "HashingEmbeddingProvider",
    "chat_contract_payload",
    "ChatHistoryStore",
    "ChatThreadAdapter",
    "FakeChatBackend",
    "FakeChatThreadAdapter",
    "PersistedTurn",
    "PersistenceError",
    "thread_key",
    "validate_thread_id",
    "ALLOWED_LABELS_AND_RELATIONSHIPS",
    "ALLOWED_PROPERTIES",
    "ALLOWED_PARAMETERS",
    "CANCELLED_TEXT",
    "INSUFFICIENT_EVIDENCE_TEXT",
    "PROVIDER_UNAVAILABLE_TEXT",
    "ChatAnswer",
    "ChatModel",
    "ChatRequest",
    "ChatResponse",
    "ChatWorkflow",
    "ChatWorkflowState",
    "EvidenceItem",
    "FakeChatModel",
    "ProviderError",
    "ProviderTransientError",
    "RetrievalLimits",
    "WorkflowError",
    "validate_generated_cypher",
    "RUN_CANCELLED",
    "RUN_FAILED",
    "RUN_QUEUED",
    "RUN_RUNNING",
    "RUN_SUCCEEDED",
    "SOURCE_DELETING",
    "SOURCE_FAILED",
    "SOURCE_INGESTING",
    "SOURCE_PENDING",
    "SOURCE_READY",
    "WORKSPACE_ACTIVE",
    "WORKSPACE_DELETING",
    "IngestionRun",
    "Source",
    "Workspace",
    "WorkspaceError",
    "WorkspaceRegistry",
    "workspace_graph_name",
]
