"""Workspace-scoped GraphRAG contracts and adapters."""

from kb_core_ui.rag.contracts import (
    AMBIGUOUS,
    EXTRACTED,
    INFERRED,
    SCHEMA_VERSION,
    Citation,
    GraphEnvelope,
    GraphNode,
    GraphRelationship,
    TextChunk,
    from_kb_core_graph,
    stable_record_id,
)
from kb_core_ui.rag.config import RagConfig
from kb_core_ui.rag.normalizer import (
    NormalizationError,
    NormalizationLimits,
    NormalizationResult,
    RejectedRecord,
    normalize_kb_core_graph,
)
from kb_core_ui.rag.falkordb_adapter import (
    AdapterError,
    AdapterHealth,
    FalkorDBAdapter,
    FalkorDBDriver,
    UnsafeCypherError,
    validate_read_only_cypher,
)
from kb_core_ui.rag.workspaces import (
    RUN_CANCELLED,
    RUN_FAILED,
    RUN_QUEUED,
    RUN_RUNNING,
    RUN_SUCCEEDED,
    SOURCE_DELETING,
    SOURCE_FAILED,
    SOURCE_INGESTING,
    SOURCE_PENDING,
    SOURCE_READY,
    WORKSPACE_ACTIVE,
    WORKSPACE_DELETING,
    IngestionRun,
    Source,
    Workspace,
    WorkspaceError,
    WorkspaceRegistry,
    workspace_graph_name,
)

__all__ = [
    "AMBIGUOUS",
    "EXTRACTED",
    "INFERRED",
    "SCHEMA_VERSION",
    "Citation",
    "GraphEnvelope",
    "GraphNode",
    "GraphRelationship",
    "TextChunk",
    "from_kb_core_graph",
    "stable_record_id",
    "RagConfig",
    "NormalizationError",
    "NormalizationLimits",
    "NormalizationResult",
    "RejectedRecord",
    "normalize_kb_core_graph",
    "AdapterError",
    "AdapterHealth",
    "FalkorDBAdapter",
    "FalkorDBDriver",
    "UnsafeCypherError",
    "validate_read_only_cypher",
    "RUN_CANCELLED",
    "RUN_FAILED",
    "RUN_QUEUED",
    "RUN_RUNNING",
    "RUN_SUCCEEDED",
    "SOURCE_DELETING",
    "SOURCE_FAILED",
    "SOURCE_INGESTING",
    "SOURCE_PENDING",
    "SOURCE_READY",
    "WORKSPACE_ACTIVE",
    "WORKSPACE_DELETING",
    "IngestionRun",
    "Source",
    "Workspace",
    "WorkspaceError",
    "WorkspaceRegistry",
    "workspace_graph_name",
]
